# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

os:
  #- linux
  - osx

before_install:
  #- sudo apt-get install -qq libzmq3-dev
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

script:
  # - ./travis-tool.sh run_tests
  - ./travis-tool.sh install_github snoweye/pbdZMQ@pbdZMQ_0.3-0
  - Rscript -e "pbdZMQ::get.zmq.cppflags()"
  - Rscript -e "pbdZMQ::get.zmq.ldflags()"
  - Rscript -e "pbdZMQ::get.pbdZMQ.ldflags()"
  - Rscript -e "pbdZMQ::test.load.zmq()"
  - otool -L /Library/Frameworks/R.framework/Versions/3.4/Resources/library/pbdZMQ/libs/pbdZMQ.so
  - otool -L /Library/Frameworks/R.framework/Versions/3.4/Resources/library/pbdZMQ/libs/libzmq.5.dylib

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: no
    on_failure: no

sudo: required
